# Generated by Django 5.2.8 on 2025-11-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('world', 'World'), ('technology', 'Technology'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('science', 'Science'), ('health', 'Health'), ('politics', 'Politics')], default='world', max_length=50)),
                ('datePublished', models.DateTimeField()),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('popularity_score', models.IntegerField(default=0)),
                ('engagementLevel', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-datePublished'],
                'indexes': [models.Index(fields=['-datePublished'], name='news_news_datePub_e74126_idx'), models.Index(fields=['category'], name='news_news_categor_05ff13_idx')],
            },
        ),
    ]
